# Generated by Django 3.2.8 on 2021-11-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('origin_user', models.IntegerField(verbose_name='Origin_User')),
                ('destiny_user', models.IntegerField(verbose_name='Destiny_User')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Resgiter_Data')),
            ],
        ),
    ]
