# Generated by Django 3.2.8 on 2021-11-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destiny_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='origin_user',
            field=models.IntegerField(),
        ),
    ]
