# Generated by Django 3.2.8 on 2021-11-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_auto_20211118_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
